sonar.projectKey=smartcourier
sonar.projectName=SmartCourier Delivery Management
sonar.sourceEncoding=UTF-8
sonar.sources=.
sonar.java.binaries=.
sonar.host.url=http://localhost:9000
sonar.inclusions=**/*.java
sonar.exclusions=**/target/**,**/.*/**
