
# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/tracking_db
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Server
server.port=8083

# RabbitMQ
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# Actuator
management.endpoints.web.exposure.include=health,info

# JWT
jwt.secret=5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437

eureka.client.initial-instance-info-replication-interval-seconds=5
eureka.client.registry-fetch-interval-seconds=5

# Enable SLF4J/Logback for your code
logging.level.com.tracking_service=INFO

# Define the log file location and rolling policy (with the %i fix!)
logging.file.name=logs/tracking-service.log
logging.logback.rollingpolicy.file-name-pattern=logs/tracking-service-%d{yyyy-MM-dd}.%i.log
logging.logback.rollingpolicy.max-history=30
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# Zipkin
management.zipkin.tracing.endpoint=http://localhost:9411/api/v2/spans
management.tracing.sampling.probability=1.0
