server:
  port: 8081

spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:postgresql://postgres-auth:5432/smartcourier?currentSchema=auth
    username: postgres
    password: SmartCourier@2024
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: smartcourier
    password: smartcourier

eureka:
  instance:
    hostname: auth-service
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/

jwt:
  secret: SmartCourierSecretKeyForJWTTokenGenerationAndValidation2024VeryLongSecureKey
  expiration: 86400000

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,tracing
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans

logging:
  level:
    root: INFO
