server:
  port: 8084

spring:
  application:
    name: admin-service
  datasource:
    url: jdbc:postgresql://postgres-admin:5432/smartcourier?currentSchema=admin
    username: postgres
    password: SmartCourier@2024
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: smartcourier
    password: smartcourier

eureka:
  instance:
    hostname: admin-service
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,tracing
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans
    brave:
      zipkin:
        url: http://zipkin:9411/api/v2/spans

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 10000
      delivery-service:
        url: http://delivery-service:8082
      tracking-service:
        url: http://tracking-service:8083
