server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: file:///config-repo
          default-label: main
          timeout: 10
          clone-on-start: false

eureka:
  instance:
    hostname: config-server
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: health,info
